export const helpFrameStyle = `
z-index: 2147483647;
position: fixed;
left: 0;
right: 0;
margin-left: auto;
margin-right: auto;
top: 5%;
/*bottom: 60px;*/
width: 400px;
max-width: 100%;
height: 90%;
border-width: 0;
background-color: white;
border-style: solid;
border-width: 1px;
border-radius: 4px;
border-color: #ff4081;
opacity: 0.95;`;
